apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: jmeter-jenkins
  labels:
    app: jmeter-jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmeter-jenkins
  template:
    metadata:
      labels:
        app: jmeter-jenkins
    spec:
      containers:
        - image: relvan/jenkins-stored
          name: jenkins
          ports:
            - containerPort: 8080
              name: jenkins
            - containerPort: 50000
              name: jenkins-slave
      nodeSelector:
        type: storage-and-monitoring
