apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: influxdb-jmeter
  labels:
    app: influxdb-jmeter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb-jmeter
  template:
    metadata:
      labels:
        app: influxdb-jmeter
    spec:
      initContainers:
      - name: permission
        image: relvan/new-inf
        command: ['sh', '-c', 'chown -R influxdb:influxdb /var/lib/influxdb']
      containers:
        - image: relvan/new-inf
          name: influxdb
          volumeMounts:
          - name: mypvc
            mountPath: /var/lib/influxdb
          ports:
            - containerPort: 8083
              name: influxd
            - containerPort: 8086
              name: api
            - containerPort: 8888
              name: chronograf
            - containerPort: 22
              name: sshd
      volumes:
      - name: mypvc
        persistentVolumeClaim:
          claimName: influxdb-claim
          readOnly: false
      nodeSelector:
        type: storage-and-monitoring
