apiVersion: v1
kind: Service
metadata:
  name: jmeter-jenkins
  labels:
    app: jenkins-jmeter
spec:
  ports:
    - port: 80
      name: jenkins
      targetPort: 8080
    - port: 50000
      name: jenkins-slave
      targetPort: 50000
  selector:
    app: jenkins-jmeter
  type: LoadBalancer
  loadBalancerIP: "35.239.18.79"
