apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: jmeter-influxdb
spec:
  ports:
    - port: 8086
      name: api
      targetPort: 8086
    - port: 22
      name: ssh
      targetPort: 22
    - port: 8888
      name: chronograf
      targetPort: 8888
  selector:
    app: jmeter-influxdb
  type: LoadBalancer
  loadBalancerIP: "35.224.73.150"
