#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: grafana-ingress
#  annotations:
#    kubernetes.io/ingress.global-static-ip-name: "grafana-service"
#spec:
#  backend:
#    serviceName: jmeter-grafana
#    servicePort: 80
#
#---
apiVersion: v1
kind: Service
metadata:
  name: jmeter-grafana
  labels:
    app: jmeter-grafana
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: jmeter-grafana
  type: LoadBalancer
  loadBalancerIP: "35.225.64.114"  
